name: Build and Release to GitHub

on:
  push:
    branches:
      - master # Or a specific release branch
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating a GitHub Release

    steps:
      # 1. Checkout repository codebase
      - name: Checkout the code
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Decode required secrets into files
      - name: Decode Keystore and Properties
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks
          echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > android/key.properties
      
      # 5. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6. Build the Android App Bundle
      - name: Build Android App Bundle
        run: |
          flutter build appbundle \
          --release \
          --build-number=${{ github.run_number }} \
          --dart-define=APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }}

      # 7. Create Github Release
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/bundle/release/app-release.aab"
          generateReleaseNotes: true
          tag: v1.0.${{ github.run_number }} # Use the build number in the tag
          token: ${{ secrets.GITHUB_TOKEN }}