name: Build and Deploy

on:
  push:
    branches:
      - master
      - deploy-actions
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 21.0.6
      FLUTTER_VERSION: 3.35.2
      APK_PATH: build/app/outputs/flutter-apk/app-release.apk
      KEYSTORE_PATH: android/upload-keystore.jks
      KEY_PROPS_PATH: android/key.properties
      FIREBASE_OPTIONS_PATH: lib/firebase_options.dart
      GOOGLE_SERVICES_ANDROID_PATH: android/app/google-services.json
      APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show disk usage before cleanup
        run: df -h /

      - name: Free disk space on runner
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Show disk usage after cleanup
        run: df -h /

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Clean Flutter project
        run: |
          flutter clean
          rm -rf build
          cd android && ./gradlew clean && cd -
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf ~/.android/build-cache

      - name: Show disk usage after cleanup
        run: df -h /

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: Decode Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: Decode Android Google Services JSON
        run: echo "${{ secrets.GOOGLE_SERVICES_ANDROID }}" | base64 --decode > ${{ env.GOOGLE_SERVICES_ANDROID_PATH }}

      - name: Decode Firebase Options
        run: echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > ${{ env.FIREBASE_OPTIONS_PATH }}

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: |
          flutter build apk --release \
          --dart-define=APPWRITE_BASE_DOMAIN=${{ secrets.APPWRITE_BASE_DOMAIN }} \
          --dart-define=APPWRITE_PROJECT_ID=${{ secrets.APPWRITE_PROJECT_ID }}

      - name: Verify APK file existence
        run: ls -lh ${{ env.APK_PATH }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: ${{ env.APK_PATH }}

  deploy_github_release:
    name: Deploy to GitHub Release
    runs-on: ubuntu-latest
    needs: build_android
    permissions:
      contents: write
    env:
      APK_RELEASE_PATH: apk-release/*.apk
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-release
          path : apk-release

      - name: Deploy to GitHub Release
        uses: ncipollo/release-action@v2
        with:
          allowUpdates: true
          artifacts: ${{ env.APK_RELEASE_PATH }}
          artifactContentType: apk
          generateReleaseNotes: true
          tag: latest_build